use_frameworks!

target 'CardStackController_Example' do
  pod 'CardStackController', :path => '../'
  pod 'Reveal'

  target 'CardStackController_Tests' do
    inherit! :search_paths

    
  end
end
